server:
  port: 8080

spring:
  application:
    name: gateway-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true



cloud:
  gateway:
    routes:
      - id: classificator-route
        uri: lb://classificator-service
        predicates:
          - Path=/api/classificator/**